elite:
  _default:
    cost_price: 2999
    discount: 10
    selling_price: 2699
    launch_date: "2025-08-01"
  E02:
    cost_price: 2999
    discount: 15
    selling_price: 2549
    launch_date: "2025-08-01"
  E07:
    cost_price: 2999
    discount: 15
    selling_price: 2549
    launch_date: "2025-08-01"
  E08:
    cost_price: 2999
    discount: 15
    selling_price: 2549
    launch_date: "2025-08-01"
  E09:
    cost_price: 2999
    discount: 15
    selling_price: 2549
    launch_date: "2025-08-01"    
prime:
  _default:
    cost_price: 1999
    discount: 15
    selling_price: 1699
    launch_date: "2025-08-01"
  P02:
    cost_price: 1999
    discount: 20
    selling_price: 1599
    launch_date: "2025-08-01"
  P07:
    cost_price: 1999
    discount: 20
    selling_price: 1599
    launch_date: "2025-08-01"
  P08:
    cost_price: 1999
    discount: 20
    selling_price: 1599
    launch_date: "2025-08-01"
  P09:
    cost_price: 1999
    discount: 20
    selling_price: 1599
    launch_date: "2025-08-01"
  P10:
    cost_price: 1999
    discount: 50
    selling_price: 999
    launch_date: "2025-08-01"
classic:
  _default:
    cost_price: 1499
    discount: 10
    selling_price: 1349
    launch_date: "2025-08-01"
